import { useEffect, useState } from 'react'

const API = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000'
const emptyForm = { title: '', destination_id: '', start_date: '', end_date: '', budget: 2500, travelers: 2, interests: '', travel_style: 'balanced' }

async function request(path, options = {}) {
  const response = await fetch(`${API}${path}`, { headers: { 'Content-Type': 'application/json' }, ...options })
  if (!response.ok) throw new Error((await response.json()).detail || 'Request failed')
  return response.json()
}

export default function App() {
  const [destinations, setDestinations] = useState([]); const [trips, setTrips] = useState([]); const [form, setForm] = useState(emptyForm)
  const [selectedTrip, setSelectedTrip] = useState(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('')
  const [expense, setExpense] = useState({ category: 'food', description: '', estimated_amount: '' })
  const [search, setSearch] = useState(''); const [searching, setSearching] = useState(false)
  const refresh = async () => { const [destinationData, tripData] = await Promise.all([request('/api/v1/destinations'), request('/api/v1/trips')]); setDestinations(destinationData); setTrips(tripData); if (selectedTrip) setSelectedTrip(tripData.find((trip) => trip.id === selectedTrip.id) || null) }
  useEffect(() => { refresh().catch((error) => setMessage(error.message)).finally(() => setLoading(false)) }, [])
  const createTrip = async (event) => { event.preventDefault(); try { const trip = await request('/api/v1/trips', { method: 'POST', body: JSON.stringify({ ...form, destination_id: Number(form.destination_id), budget: Number(form.budget), travelers: Number(form.travelers) }) }); setForm(emptyForm); setSelectedTrip(trip); setMessage('Trip created. Generate an itinerary when you are ready.'); await refresh() } catch (error) { setMessage(error.message) } }
  const generate = async () => { try { const trip = await request(`/api/v1/trips/${selectedTrip.id}/generate`, { method: 'POST' }); setSelectedTrip(trip); await refresh(); setMessage('Your day-by-day plan is ready.') } catch (error) { setMessage(error.message) } }
  const addExpense = async (event) => { event.preventDefault(); try { const trip = await request(`/api/v1/trips/${selectedTrip.id}/expenses`, { method: 'POST', body: JSON.stringify({ ...expense, estimated_amount: Number(expense.estimated_amount) }) }); setSelectedTrip(trip); setExpense({ category: 'food', description: '', estimated_amount: '' }); await refresh(); setMessage('Expense added to your trip budget.') } catch (error) { setMessage(error.message) } }
  const findPlaces = async (event) => { event.preventDefault(); if (search.trim().length < 2) return; setSearching(true); try { const matches = await request(`/api/v1/destinations/search?q=${encodeURIComponent(search)}`); setDestinations(matches); setMessage(`${matches.length} destinations found. Pick one to use in your trip.`) } catch (error) { setMessage('Destination search is temporarily unavailable.') } finally { setSearching(false) } }
  if (loading) return <div className="loading">Loading your travel workspace...</div>
  return <main className="app-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">T</span><span>TripIQ</span></div><div className="status"><span className="pulse" /> Planning workspace <span className="avatar">DT</span></div></header>
    <section className="hero"><div><p className="eyebrow">YOUR TRAVEL OPERATING SYSTEM</p><h1>Make the next trip<br /><em>feel inevitable.</em></h1><p className="hero-copy">Turn a destination, a budget, and a few preferences into a trip you can actually look forward to.</p></div><div className="hero-stat"><strong>{trips.length}</strong><span>trips in your workspace</span></div></section>
    {message && <div className="notice">{message}</div>}
    <div className="workspace"><section className="panel planner"><div className="panel-heading"><div><p className="eyebrow">01 / START PLANNING</p><h2>Build a new trip</h2></div><span className="step">2 min setup</span></div>
      <form onSubmit={createTrip} className="trip-form"><label>Trip name<input required placeholder="Summer in Japan" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>Destination<select required value={form.destination_id} onChange={(e) => setForm({ ...form, destination_id: e.target.value })}><option value="">Choose a place</option>{destinations.map((destination) => <option key={destination.id} value={destination.id}>{destination.name}, {destination.country}</option>)}</select></label><div className="form-row"><label>Start date<input required type="date" value={form.start_date} onChange={(e) => setForm({ ...form, start_date: e.target.value })} /></label><label>End date<input required type="date" value={form.end_date} onChange={(e) => setForm({ ...form, end_date: e.target.value })} /></label></div><div className="form-row"><label>Budget (USD)<input required type="number" min="1" value={form.budget} onChange={(e) => setForm({ ...form, budget: e.target.value })} /></label><label>Travelers<input required type="number" min="1" max="20" value={form.travelers} onChange={(e) => setForm({ ...form, travelers: e.target.value })} /></label></div><label>What are you into?<input placeholder="Food, design, hiking..." value={form.interests} onChange={(e) => setForm({ ...form, interests: e.target.value })} /></label><label>Travel style<select value={form.travel_style} onChange={(e) => setForm({ ...form, travel_style: e.target.value })}><option value="balanced">Balanced</option><option value="slow">Slow and local</option><option value="packed">Packed with highlights</option><option value="luxury">Comfort first</option></select></label><button className="primary" type="submit">Create trip <span>↗</span></button></form>
    </section><section className="panel destinations"><div className="panel-heading"><div><p className="eyebrow">02 / SEARCH THE WORLD</p><h2>Where to next?</h2></div></div><form className="search-box" onSubmit={findPlaces}><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search any city or country..." /><button className="primary compact" type="submit">{searching ? 'Searching...' : 'Search'}</button></form><div className="destination-grid">{destinations.map((destination) => <button className={`destination-card ${String(form.destination_id) === String(destination.id) ? 'chosen' : ''}`} key={destination.id} onClick={() => setForm({ ...form, destination_id: String(destination.id) })}><div className={`destination-image image-${destination.id % 5}`}><span>{destination.category}</span></div><div className="destination-info"><strong>{destination.name}</strong><span>{destination.country}</span><small>From ${destination.average_daily_cost}/day</small></div></button>)}</div></section></div>
    <section className="panel trips-panel"><div className="panel-heading"><div><p className="eyebrow">03 / YOUR JOURNEYS</p><h2>Trips in motion</h2></div></div>{trips.length === 0 ? <div className="empty">Your first trip is one good idea away.</div> : <div className="trip-list">{trips.map((trip) => <button className={`trip-row ${selectedTrip?.id === trip.id ? 'selected' : ''}`} key={trip.id} onClick={() => setSelectedTrip(trip)}><span className="trip-number">0{trip.id}</span><span className="trip-name"><strong>{trip.title}</strong><small>{trip.destination}, {trip.country} · {trip.start_date}</small></span><span className="trip-status">{trip.status}</span><span>→</span></button>)}</div>}</section>
    {selectedTrip && <section className="panel detail-panel"><div className="detail-header"><div><p className="eyebrow">TRIP DETAIL</p><h2>{selectedTrip.title}</h2><p>{selectedTrip.destination}, {selectedTrip.country} · ${selectedTrip.budget} budget · {selectedTrip.travelers} travelers</p></div><button className="primary compact" onClick={generate}>Generate itinerary ↗</button></div>{selectedTrip.itinerary?.days?.length ? <div className="itinerary">{selectedTrip.itinerary.days.map((day) => <article key={day.day}><span>DAY {String(day.day).padStart(2, '0')}</span><div><h3>{day.title}</h3><p>{day.activities.join(' · ')}</p></div></article>)}</div> : <div className="empty">No itinerary yet. Generate one from your trip preferences.</div>}<div className="expense-area"><p className="eyebrow">BUDGET TRACKER</p><h3>Trip expenses</h3><form className="expense-form" onSubmit={addExpense}><select value={expense.category} onChange={(e) => setExpense({ ...expense, category: e.target.value })}><option value="food">Food</option><option value="stay">Stay</option><option value="transport">Transport</option><option value="activity">Activity</option></select><input required placeholder="What did you book?" value={expense.description} onChange={(e) => setExpense({ ...expense, description: e.target.value })} /><input required type="number" min="1" placeholder="Amount" value={expense.estimated_amount} onChange={(e) => setExpense({ ...expense, estimated_amount: e.target.value })} /><button className="primary compact" type="submit">Add</button></form>{selectedTrip.expenses?.map((item) => <div className="expense-item" key={item.id}><span>{item.category} · {item.description}</span><strong>${item.estimated_amount}</strong></div>)}</div></section>}
  </main>
}
